In [1]:
import torch

## 创建一个张量，设置requires_grad=True来跟踪与它相关的计算

In [7]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


## 针对张量做一个操作

In [8]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


## y作为被操作的结果被创建，所以它有grad_fn

In [10]:
z = y * y * 3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


## .requires_grad(..)会改变张量的requires_grad标记。输入的标记默认为False,如果没有提供相应的参数。

In [12]:
a = torch.randn(2,2)
a = (a *3 )/(a -1)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [13]:
out.backward()#向后传播，等同于out.backward(torch.Tensor(1.)),输出包含了一个标量

In [14]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


## 雅克比向量积

In [25]:
x =torch.randn(3,requires_grad=True)
y=x*2
while y.data.norm() < 1000:
    y=y*2
print(y)

tensor([  455.3151,   395.4816, -1547.5536], grad_fn=<MulBackward0>)


## 在这种情况下，y不再是一个向量。torch.autograd不能够直接计算整个雅克比，但是如果我们只想要雅克比向量积，只需要简单的传递向量给backward作为参数

In [26]:
v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float,requires_grad=True)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


## 将代码包裹在with_torch.no_grad(),来停止对从跟踪历史中的.requires_grad=True的张量自动求导

In [29]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad) 

True
True
False
