In [25]:
import torch
import numpy as np

# PyTorch基本数据类型

In [26]:
a = torch.randn(2,3)
a.type()

'torch.FloatTensor'

## 参数检验

In [27]:
isinstance(a,torch.FloatTensor)

True


## 标量,dimension为0，eg计算误差loss时

In [28]:
torch.tensor(1.)

tensor(1.)

In [29]:
torch.tensor(1.3)

tensor(1.3000)

In [30]:
b=torch.tensor(2.2)
b.shape

torch.Size([])

In [31]:
len(b.shape)

0

In [32]:
b.dim()

0

In [33]:
b.size()

torch.Size([])

## dimension为1,eg,Bias,偏置;神经网络线性输入

In [34]:
torch.tensor([1.1])

tensor([1.1000])

In [35]:
torch.tensor([1.1,2.2])

tensor([1.1000, 2.2000])

In [36]:
torch.FloatTensor(1) #随机初始化

tensor([1.1000])

In [37]:
torch.FloatTensor(2)

tensor([0., 0.])

In [38]:
data =np.ones(2)
data

array([1., 1.])

In [39]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [40]:
a=torch.ones(2)

In [41]:
a.shape

torch.Size([2])

dimension：eg二维行和列;size/shape具体形状[2,2];tensor:具体数据

## dimesion为2 eg,linear input batch

In [45]:
c=torch.randn(2,3)
c

tensor([[ 0.3345,  2.1185,  0.7922],
        [ 1.3190, -1.3794, -0.4058]])

In [52]:
c.shape

torch.Size([2, 3])

In [53]:
c.size(0)

2

In [54]:
c.size(1)

3

In [55]:
c.shape[1] #对shape进行索引

3

## dimension为3 eg, RNN input batch

In [56]:
d=torch.rand(1,2,3)
d

tensor([[[0.9304, 0.7909, 0.5167],
         [0.5552, 0.9735, 0.3432]]])

In [57]:
d.shape

torch.Size([1, 2, 3])

In [58]:
d[0]

tensor([[0.9304, 0.7909, 0.5167],
        [0.5552, 0.9735, 0.3432]])

In [59]:
list(d.shape)

[1, 2, 3]

## Dimension为4，适合图片eg.CNN [b,c,h,w]

In [62]:
e=torch.rand(2,3,28,28)#28*28,图片长宽，3代表通道RGB，2代表2张照片 [batch,channel.height.weighth],适合卷积神经网络
e

tensor([[[[0.6811, 0.3725, 0.9168,  ..., 0.5270, 0.1414, 0.9535],
          [0.4592, 0.2653, 0.5756,  ..., 0.0771, 0.9350, 0.8320],
          [0.7568, 0.2955, 0.3753,  ..., 0.9046, 0.6161, 0.5191],
          ...,
          [0.9835, 0.2756, 0.4478,  ..., 0.9845, 0.6428, 0.4608],
          [0.7401, 0.9897, 0.5383,  ..., 0.1886, 0.2317, 0.8230],
          [0.0569, 0.5405, 0.3870,  ..., 0.5507, 0.6816, 0.9340]],

         [[0.9420, 0.9554, 0.3571,  ..., 0.2346, 0.3221, 0.7390],
          [0.8999, 0.5828, 0.5915,  ..., 0.5964, 0.5815, 0.1366],
          [0.6351, 0.8604, 0.6905,  ..., 0.8597, 0.5351, 0.3339],
          ...,
          [0.2014, 0.7845, 0.0470,  ..., 0.7053, 0.9324, 0.1873],
          [0.2958, 0.0393, 0.1077,  ..., 0.3186, 0.9842, 0.3359],
          [0.0048, 0.7742, 0.6835,  ..., 0.3363, 0.3447, 0.0031]],

         [[0.8524, 0.1225, 0.6456,  ..., 0.7566, 0.3619, 0.6459],
          [0.6676, 0.1592, 0.8735,  ..., 0.2162, 0.9637, 0.7763],
          [0.3543, 0.6444, 0.0888,  ..., 0

In [66]:
e.shape

torch.Size([2, 3, 28, 28])

In [68]:
e.numel()#number of element 2*3*28*28=4708

4704

In [69]:
e.dim()#返回dimension

4