In [3]:
import numpy as np
import torch

## 先用Numpy创建，再导入成tensor

In [9]:
a=np.array([2.,3.3])

In [10]:
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [11]:
a=np.ones([2,3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [12]:
torch.FloatTensor(3,1,28,28)#用,形式没有初始化，以List形式给会进行初始化

tensor([[[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          ...,
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          ...,
   

In [13]:
torch.IntTensor(3,1,28,28)

tensor([[[[    2621470,    17236108,     7340031,  ...,    15204671,
              20709432,     3866623],
          [   17105199,     8782153,    11862179,  ...,     1638408,
              13697244,    21037193],
          [   13107532,    14614641,          -1,  ...,     3342436,
              11665634,    10420504],
          ...,
          [-1749420815, -1088855381, -1795086352,  ..., -1601331981,
           -1795007312,         484],
          [-1795077680,         484,   133361060,  ...,         484,
            1891160674,  -251282165],
          [-1792259408,         484, -1792207328,  ...,         484,
           -1792265744,         484]]],


        [[[ 1506473628,  -264395908, -1792286032,  ..., -2073673114,
           -1828760784,         484],
          [-1792171424,         484,  -950419406,  ...,         484,
            1519378523, -1895094238],
          [-1795007552,         484, -1792037888,  ...,         484,
           -1791623936,         484],
          ...,
   

In [14]:
torch.empty(1)

tensor([0.])

In [16]:
torch.Tensor(2,3)#没有初始化的数据可能非常大也可能非常小，数据不规则

tensor([[5.3640e-08, 2.6729e+23, 2.6251e-09],
        [8.3899e-07, 3.3207e-09, 8.1935e-10]])